// <auto-generated />
namespace Library.DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ChangetosingpeefmodelHashSet : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ChangetosingpeefmodelHashSet));
        
        string IMigrationMetadata.Id
        {
            get { return "201803241705110_Change to singpe ef model.(HashSet)"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
