// <auto-generated />
namespace Library.DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ChangetooldrelationsinBooktoAuthors : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ChangetooldrelationsinBooktoAuthors));
        
        string IMigrationMetadata.Id
        {
            get { return "201803261452353_Change to old relations in Book to Authors."; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
