// <auto-generated />
namespace Library.DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Updateforidentity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Updateforidentity));
        
        string IMigrationMetadata.Id
        {
            get { return "201804041528510_Update for identity."; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
