// <auto-generated />
namespace Library.DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _4thtaskwithpublicationhouses : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_4thtaskwithpublicationhouses));
        
        string IMigrationMetadata.Id
        {
            get { return "201803280818580_4-th task with publication houses."; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
